kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dify-pvc
  namespace: dify
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi