apiVersion: v1
kind: PersistentVolume
metadata:
  name: dify
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  nfs:
    path: /data/nfs
    server: <NFS_SERVER_IP>