apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-pvc
  namespace: dify
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  volumeName: dify
  resources:
    requests:
      storage: 10Gi