apiVersion: v1
kind: PersistentVolume
metadata:
  name: dify
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs_share
    server: 10.0.2.15