apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dify
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432